import { renderToStaticMarkup } from "react-dom/server";
import { download } from "./exchange";
import { occupant, type StudioLayout } from "./schema";
function svgCopy(svg:SVGSVGElement){const copy=svg.cloneNode(true) as SVGSVGElement;copy.setAttribute("xmlns","http://www.w3.org/2000/svg");copy.setAttribute("width","1800");copy.setAttribute("height","1200");copy.querySelectorAll("[tabindex]").forEach(e=>e.removeAttribute("tabindex"));return new XMLSerializer().serializeToString(copy);}
export const exportPlanSvg=(svg:SVGSVGElement)=>download("glass-house-plan.svg",svgCopy(svg),"image/svg+xml");
export async function exportPlanPng(svg:SVGSVGElement){
  const source=URL.createObjectURL(new Blob([svgCopy(svg)],{type:"image/svg+xml"}));
  try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error("Unable to render SVG for PNG export."));image.src=source;});const canvas=document.createElement("canvas");canvas.width=1800;canvas.height=1200;const ctx=canvas.getContext("2d");if(!ctx)throw Error("Canvas export unavailable.");ctx.fillStyle="#f0eee5";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)throw Error("PNG export failed.");download("glass-house-plan.png",blob,"image/png");}finally{URL.revokeObjectURL(source);}
}
export function exportSeatingHtml(layout:StudioLayout,tableId?:string){
  const tables=layout.items.filter(t=>t.kind==="table"&&(!tableId||t.id===tableId));
  const markup=renderToStaticMarkup(<html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Glass House seating list</title><style>{"body{font:14px/1.6 Arial,sans-serif;max-width:980px;margin:30px auto;padding:20px;color:#254633}h1,h2{font-family:Georgia,serif}section{break-inside:avoid;margin:24px 0}table{border-collapse:collapse;width:100%}th,td{text-align:left;border-bottom:1px solid #ddd;padding:8px}small{color:#777}@media print{body{padding:0;margin:0}}"}</style></head><body><h1>{layout.title}</h1><p>Current draft seating · contains private guest information</p>{tables.map(t=><section key={t.id}><h2>Table {t.label}</h2><table><thead><tr><th>Seat</th><th>Guest</th><th>Group</th><th>Dietary / notes</th></tr></thead><tbody>{Array.from({length:t.seats},(_,i)=>{const g=occupant(layout,{tableId:t.id,seatNumber:i+1});return <tr key={i}><td>{i+1}</td><td>{g?.name??"Empty"}</td><td>{g?[g.host,g.group].filter(Boolean).join(" · "):""}</td><td>{g?[g.dietary,g.notes].filter(Boolean).join(" · "):""}</td></tr>;})}</tbody></table></section>)}{!tableId&&<section><h2>Unassigned / reserve</h2>{layout.guestList.filter(g=>!g.tableId).map(g=><p key={g.id}>{g.name} · {g.group}{g.reserve?" · Reserve":""}</p>)}</section>}<small>Architectural approximation. Confirm seating and circulation with the venue.</small></body></html>);
  download(tableId?`${tableId}-seating.html`:"glass-house-seating.html","<!doctype html>"+markup,"text/html;charset=utf-8");
}
