import { expect, test, type Page } from "@playwright/test";
import { normalizeLayout } from "../../src/client/studio/model/schema";
test.use({launchOptions:{args:["--enable-unsafe-swiftshader"]}});
test.describe.configure({timeout:60_000});
async function chooseView(page:Page,name:string){await page.getByRole("button",{name:"View panel",exact:true}).click();await page.getByRole("button",{name,exact:true}).click();}
async function open(page:Page){
  const layout=normalizeLayout({version:3,title:"Synthetic mobile scene",units:"metres",items:[{id:"table-1",kind:"table",shape:"oval",label:"1",x:0,z:0,w:2,d:1.2,h:.76,rotation:0,seats:10,locked:false}],guestList:[{id:"mobile-alice",name:"Alice",tableId:"table-1",seatNumber:1},{id:"mobile-thai",name:"แขกทดสอบชื่อยาวสำหรับมือถือ",tableId:"table-1",seatNumber:6},...Array.from({length:45},(_,i)=>({id:`synthetic-${i}`,name:`Synthetic guest ${i}`}))]});
  const writes:string[]=[];
  await page.route("**/api/admin/studio/layout",route=>route.fulfill({json:{status:"ok",source:"Google Sheets",layout,revision:"mobile-test",fetchedAt:Date.now()}}));
  await page.route("**/api/admin/studio/mutations",async route=>{writes.push(route.request().postData()??"");await route.fulfill({status:409,json:{error:{message:"Camera gestures must not write seating data."}}});});
  await page.goto("/admin/studio");await page.getByLabel("Administrator passphrase").fill("local-e2e-passphrase");await page.getByRole("button",{name:"Open studio",exact:true}).click();await expect(page.locator(".studio-plan .studio-name-badge")).toHaveCount(2);
  await chooseView(page,"3D model");await expect(page.locator(".studio-three-view canvas")).toBeVisible();await expect(page.locator('.studio-seat-name-label[data-guest-drag="mobile-alice"]')).toBeVisible({timeout:20_000});return writes;
}
const viewportBounds=async(page:Page)=>{const bounds=await page.locator(".studio-three-view canvas").boundingBox(),screen=page.viewportSize()!;expect(bounds!.x).toBeLessThanOrEqual(1);expect(bounds!.y).toBeLessThanOrEqual(1);expect(bounds!.width).toBeGreaterThanOrEqual(screen.width-2);expect(bounds!.height).toBeGreaterThanOrEqual(screen.height-2);};
const frame=(page:Page)=>page.locator(".studio-three-view canvas").evaluate((canvas:HTMLCanvasElement)=>{const gl=canvas.getContext("webgl2");if(!gl||gl.isContextLost())throw Error("An active WebGL renderer is required");const pixel=new Uint8Array(4),samples:number[]=[];for(const x of [.1,.2,.35,.5,.65,.8,.9])for(const y of [.15,.3,.45,.6,.75,.9]){gl.readPixels(Math.floor(x*canvas.width),Math.floor(y*canvas.height),1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);samples.push(...pixel);}return samples.join(",");});
test("scene fills the viewport rather than sharing a scrolling page with tool panels",async({page})=>{await open(page);await viewportBounds(page);expect(await page.locator(".studio-three-view canvas").evaluate(el=>getComputedStyle(el).touchAction)).toBe("none");expect(await page.evaluate(()=>getComputedStyle(document.documentElement).overflow)).toBe("hidden");});
test("walk mode has an on-screen analogue joystick",async({page})=>{await open(page);await chooseView(page,"Walk inside");await expect(page.getByRole("group",{name:"Walk joystick",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Hold to walk forward",exact:true})).toHaveCount(0);});
test("guest sheet is independently scrollable and never resizes the scene",async({page},testInfo)=>{
  const writes=await open(page);await page.getByRole("button",{name:"Guests panel",exact:true}).click();await expect(page.getByRole("complementary",{name:"Planning tools"})).toBeVisible();await viewportBounds(page);
  const scrolling=page.locator('.studio-sidebar-scroll');expect(await scrolling.evaluate(el=>getComputedStyle(el).touchAction)).toBe("pan-y");await scrolling.evaluate(el=>{el.scrollTop=10000;});expect(await scrolling.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);expect(await page.evaluate(()=>scrollY)).toBe(0);
  await testInfo.attach("fullscreen-guest-sheet",{body:await page.screenshot({path:testInfo.outputPath("fullscreen-guest-sheet.png")}),contentType:"image/png"});await page.getByRole("button",{name:"Close planning tools",exact:true}).click();await expect(page.getByRole("complementary",{name:"Planning tools"})).toBeHidden();await viewportBounds(page);expect(writes).toHaveLength(0);
});
test("scene touch gestures orbit without scrolling or changing assignments",async({page,isMobile})=>{
  const writes=await open(page),screen=page.viewportSize()!,start={x:screen.width*.76,y:screen.height*.53},end={x:screen.width*.82,y:screen.height*.65},before=await frame(page);
  if(isMobile){const session=await page.context().newCDPSession(page);await session.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[start]});for(let i=1;i<=8;i++)await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8}]});await session.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await session.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:8});await page.mouse.up();}
  await expect.poll(()=>frame(page),{timeout:15_000}).not.toBe(before);expect(await page.evaluate(()=>({x:scrollX,y:scrollY}))).toEqual({x:0,y:0});expect(writes).toHaveLength(0);
});
test("mobile names use bounded pixels, retain full accessible names and let walk gestures through",async({page,isMobile},testInfo)=>{
  await open(page);const name=page.locator('.studio-seat-name-label[data-guest-drag="mobile-thai"]');await expect(name).toHaveText("แขกทดสอบชื่อยาวสำหรับมือถือ");await expect(name).toHaveAttribute("title","แขกทดสอบชื่อยาวสำหรับมือถือ");
  if(isMobile){await expect(name).toHaveAttribute("data-compact","true");const size=await name.boundingBox();expect(size!.width).toBeLessThanOrEqual(105);expect(size!.height).toBeLessThanOrEqual(45);expect(await name.evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(11);}
  await testInfo.attach("responsive-seat-names",{body:await page.screenshot({path:testInfo.outputPath("responsive-seat-names.png")}),contentType:"image/png"});await chooseView(page,"Walk inside");const walkName=page.locator('.studio-seat-name-label[data-seat-number="1"]');await expect(walkName).toHaveAttribute("data-walking","true");expect(await walkName.evaluate(el=>getComputedStyle(el).pointerEvents)).toBe("none");
});
test("joystick moves while a second finger looks, then cancels cleanly",async({page,isMobile},testInfo)=>{
  const writes=await open(page);await chooseView(page,"Walk inside");const stick=page.getByRole("group",{name:"Walk joystick",exact:true});await expect(stick).toBeVisible();const r=await stick.boundingBox(),screen=page.viewportSize()!,start={x:r!.x+r!.width/2,y:r!.y+r!.height/2},move={x:start.x+10,y:start.y-36},before=await frame(page);
  if(isMobile){const session=await page.context().newCDPSession(page);await session.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{...start,id:1}]});await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{...move,id:1}]});const look={x:screen.width*.72,y:screen.height*.46,id:2};await session.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{...move,id:1},look]});for(let i=1;i<=4;i++)await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{...move,id:1},{x:look.x+i*10,y:look.y+i*2.5,id:2}]});await expect(stick).toHaveAttribute("data-active","true");await expect.poll(()=>frame(page),{timeout:15_000}).not.toBe(before);await session.send("Input.dispatchTouchEvent",{type:"touchCancel",touchPoints:[]});await session.detach();}
  else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(move.x,move.y,{steps:2});await expect(stick).toHaveAttribute("data-active","true");await expect.poll(()=>frame(page),{timeout:15_000}).not.toBe(before);await page.mouse.up();}
  await expect(stick).toHaveAttribute("data-active","false");expect(await stick.locator('.studio-joystick-knob').evaluate(el=>getComputedStyle(el).transform)).toBe("matrix(1, 0, 0, 1, 0, 0)");await page.getByRole("button",{name:"Guests panel",exact:true}).click();await expect(stick).toBeHidden();await page.getByRole("button",{name:"Close planning tools",exact:true}).click();await expect(stick).toBeVisible();await expect(stick).toHaveAttribute("data-active","false");
  await testInfo.attach("walking-joystick",{body:await page.screenshot({path:testInfo.outputPath("walking-joystick.png")}),contentType:"image/png"});expect(writes).toHaveLength(0);expect(await page.evaluate(()=>scrollY)).toBe(0);
});
test("landscape keeps the scene full size and document styles restore on leaving",async({page})=>{await open(page);await page.setViewportSize({width:844,height:390});await viewportBounds(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole("button",{name:"More panel",exact:true}).click();await page.getByRole("link",{name:"Back to admin dashboard"}).click();await expect(page.locator('.studio-immersive')).toHaveCount(0);expect(await page.evaluate(()=>document.body.style.position)).not.toBe("fixed");expect(await page.evaluate(()=>document.documentElement.style.overflow)).not.toBe("hidden");});
