import { useState } from "react";
import { distributeGuests, moveGuests } from "../model/commands";
import { tableGuests } from "../model/schema";
import { useStudio } from "../state/StudioProvider";
import { GuestGrip, useDropTarget } from "../interaction/GuestDragProvider";
export function GuestRoster(){
  const {layout,picked,setPicked,commit,setModal,notify}=useStudio(),[query,setQuery]=useState(""),[filter,setFilter]=useState("needs"),[source,setSource]=useState(""),[destination,setDestination]=useState(""),[split,setSplit]=useState<string[]>([]);
  const tables=layout.items.filter(t=>t.kind==="table"),unassigned=useDropTarget({tableId:""});
  const visible=layout.guestList.filter(g=>(filter==="all"||filter==="needs"&&!g.tableId&&!g.reserve&&g.rsvp!=="Declined"||filter==="assigned"&&!!g.tableId||filter==="reserve"&&g.reserve)&&(!source||g.sourceTableId===source)&&`${g.name} ${g.host} ${g.group} ${g.sourceTableLabel}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>(a.sourceSeatNumber??999)-(b.sourceSeatNumber??999));
  function distribute(){const ids=visible.filter(g=>picked.includes(g.id)).map(g=>g.id);const other=picked.filter(id=>!ids.includes(id));const order=[...ids,...other];try{distributeGuests(layout,order,split);if(confirm(`Move ${order.length} selected guests into ${split.length} selected tables in this order?`)){commit("Group distributed",s=>distributeGuests(s,order,split));setPicked([]);}}catch(cause){notify(cause instanceof Error?cause.message:"Unable to distribute guests.");}}
  return <section className="studio-roster"><div className="studio-row"><h2>Seat your guests.</h2><button onClick={()=>setModal({type:"guest"})}>+ Guest</button></div>
    <p>{layout.guestList.length} guests · {layout.guestList.filter(g=>g.tableId).length} seated · {layout.guestList.filter(g=>g.reserve).length} reserve</p>
    <p className="studio-note">Drag a grip or occupied name onto a chair to move / swap. Source tables and this draft are different plans; no automatic mapping.</p>
    <input type="search" placeholder="Name, group or original table…" aria-label="Search guest book" value={query} onChange={e=>setQuery(e.target.value)}/>
    <div className="studio-form-grid"><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="needs">Need seats</option><option value="all">All guests</option><option value="assigned">Seated</option><option value="reserve">Reserve</option></select></label><label>Original group<select value={source} onChange={e=>setSource(e.target.value)}><option value="">All source tables</option>{Array.from(new Set(layout.guestList.map(g=>g.sourceTableId).filter(Boolean))).map(id=><option key={id} value={id}>{layout.guestList.find(g=>g.sourceTableId===id)?.sourceTableLabel||id}</option>)}</select></label></div>
    <div className="studio-unassigned" {...unassigned}>↙ Drop here to unassign · records are kept</div>
    <div className="studio-row"><label><input type="checkbox" checked={visible.length>0&&visible.every(g=>picked.includes(g.id))} onChange={e=>setPicked(e.target.checked?Array.from(new Set([...picked,...visible.map(g=>g.id)])):picked.filter(id=>!visible.some(g=>g.id===id)))}/> {visible.length} shown</label><button onClick={()=>setPicked([])} disabled={!picked.length}>Clear {picked.length} selected</button></div>
    {!!picked.length&&<div className="studio-bulk"><select aria-label="Bulk target table" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose table</option>{tables.map(t=><option key={t.id} value={t.id}>Table {t.label} · {t.seats-tableGuests(layout,t.id).length} free</option>)}</select><button disabled={!destination} onClick={()=>commit("Guests assigned",s=>moveGuests(s,picked,{tableId:destination}))}>Assign</button><button onClick={()=>commit("Guests unassigned",s=>moveGuests(s,picked,{tableId:""}))}>Unassign</button><button className="danger" onClick={()=>{if(confirm(`Remove ${picked.length} guests from the roster? Undo is available.`)){const ids=picked.slice();commit("Guests removed",s=>({...s,guestList:s.guestList.filter(g=>!ids.includes(g.id))}));setPicked([]);}}}>Remove</button></div>}
    <div className="studio-roster-list">{visible.map(g=><div className="studio-roster-row" key={g.id}><GuestGrip id={g.id} bulk/><input type="checkbox" aria-label={`Select ${g.name}`} checked={picked.includes(g.id)} onChange={e=>setPicked(e.target.checked?[...picked,g.id]:picked.filter(id=>id!==g.id))}/><button onClick={()=>setModal({type:"guest",id:g.id})}><strong>{g.name}{g.vip?" ★":""}</strong><small>{g.host} · {g.group}{g.tableId?` · Table ${layout.items.find(t=>t.id===g.tableId)?.label}, seat ${g.seatNumber}`:" · Unassigned"}</small></button></div>)}{!visible.length&&<p className="studio-note">No guests match. Import your saved layout or the site roster to begin.</p>}</div>
    <details><summary>Split selected guests across tables</summary><p className="studio-note">Selection order below determines placement order. Review capacity before applying. Existing assignments of selected guests will be moved.</p><div className="studio-split-tables">{tables.map(t=><label key={t.id}><input type="checkbox" checked={split.includes(t.id)} onChange={e=>setSplit(e.target.checked?[...split,t.id]:split.filter(id=>id!==t.id))}/>Table {t.label}</label>)}</div><button onClick={distribute} disabled={!picked.length||!split.length}>Review &amp; distribute {picked.length} guests</button></details>
  </section>;
}
