import type { FormEvent } from "react";
import { newItem } from "../model/defaults";
import { removeItem } from "../model/commands";
import { normalizeLayout, type StudioItem } from "../model/schema";
import { useStudio } from "../state/StudioProvider";
export function ObjectInspector(){
  const {layout,revision,selected,setSelected,commit,setModal,notify}=useStudio(),item=layout.items.find(o=>o.id===selected);
  if(!item)return <section><h3>Select a table or event zone</h3><p>Click an object in the floor plan or select it in the list. Drag guests from the Guests tab, independently of furniture.</p></section>;
  function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!item)return;const form=new FormData(e.currentTarget),patch:StudioItem={...item,label:String(form.get("label")??item.label)};
    if(!item.locked){for(const k of ["x","z","w","d","h","rotation","seats"] as const)if(form.has(k))patch[k]=Number(form.get(k));patch.shape=String(form.get("shape")??item.shape) as StudioItem["shape"];if(patch.shape==="round")patch.d=patch.w;if(item.kind==="aisle")patch.aisleWidth=Number(form.get("aisleWidth"));}
    try{normalizeLayout({...layout,items:layout.items.map(i=>i.id===item.id?patch:i)});commit("Object updated",s=>({...s,items:s.items.map(i=>i.id===item.id?patch:i)}));}catch(cause){notify(cause instanceof Error?cause.message:"Invalid object.");}}
  return <section><h2>{item.kind==="table"?"Table ":""}{item.label}</h2><form key={`${item.id}:${revision}`} className="studio-form" onSubmit={save}><label>Label<input name="label" defaultValue={item.label} maxLength={80}/></label><fieldset disabled={item.locked}><div className="studio-form-grid">{(["x","z","w","d","h","rotation"] as const).map(k=><label key={k}>{({x:"X (m)",z:"Z (m)",w:"Width (m)",d:"Depth (m)",h:"Height (m)",rotation:"Rotation (°)"})[k]}<input name={k} type="number" required step={k==="rotation"?1:.01} defaultValue={Number(item[k].toFixed(3))}/></label>)}<label>Shape<select name="shape" defaultValue={item.shape}><option value="oval">Oval</option><option value="round">Round</option><option value="rect">Rectangle</option></select></label>{item.kind==="table"&&<label>Seats<input name="seats" type="number" min={1} max={16} step={1} defaultValue={item.seats}/></label>}{item.kind==="aisle"&&<label>Aisle width<input name="aisleWidth" type="number" min={.4} max={Math.min(item.w,item.d)} step={.05} defaultValue={item.aisleWidth}/></label>}</div></fieldset><button type="submit" className="primary">Apply dimensions</button></form>
    <label className="studio-check"><input type="checkbox" checked={item.locked} onChange={e=>{const locked=e.target.checked;commit(locked?"Object locked":"Object unlocked",s=>({...s,items:s.items.map(i=>i.id===item.id?{...i,locked}:i)}));}}/> Lock furniture position / size</label>
    {item.kind==="table"&&<button className="primary" onClick={()=>setModal({type:"seat",target:{tableId:item.id,seatNumber:1}})}>Open seat-by-seat map</button>}
    <div className="studio-row"><button onClick={()=>{const fresh=newItem(item.kind,layout.items),copy={...item,id:fresh.id,label:item.kind==="table"?fresh.label:`${item.label} copy`.slice(0,80),x:Math.min(40,item.x+1),z:Math.min(30,item.z+1),locked:false,guests:[]};commit("Object duplicated without copying guest assignments",s=>({...s,items:[...s.items,copy]}),()=>setSelected(copy.id));}}>Duplicate</button><button className="danger" disabled={item.locked} onClick={()=>commit("Object removed; guests retained",s=>removeItem(s,item.id),()=>setSelected(null))}>Delete</button></div>
  </section>;
}
