import { useMemo, useState } from "react";
import { defaultLayout, newItem } from "../model/defaults";
import { conflicts } from "../model/geometry";
import { kinds, tableGuests, type ViewOptions } from "../model/schema";
import { useStudio } from "../state/StudioProvider";
import { GuestRoster } from "./GuestRoster";
import { ObjectInspector } from "./ObjectInspector";
export function StudioSidebar(){
  const {layout,selected,setSelected,commit,options,setOptions,view}=useStudio(),[tab,setTab]=useState("layout"),[open,setOpen]=useState(false),warnings=useMemo(()=>conflicts(layout),[layout]);
  const boolOptions:[keyof Pick<ViewOptions,"furniture"|"chairs"|"guestNames"|"tableLabels"|"grid"|"snap"|"garden">,string][]=[["furniture","Furniture & zones"],["chairs","Chairs"],["guestNames","Guest-name labels"],["tableLabels","Table labels"],["grid","1 m grid"],["snap","Snap furniture to 0.1 m"],["garden","Garden context"]];
  return <><button className="studio-mobile-tools" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?"Close tools ↓":"Guests & planning tools ↑"}</button><aside className={`studio-sidebar ${open?"open":""}`} aria-label="Planning tools">
    <nav className="studio-sidebar-tabs">{["layout","guests","selected","layers"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    <div className="studio-sidebar-scroll">{tab==="guests"?<GuestRoster/>:tab==="selected"?<ObjectInspector/>:tab==="layers"?<section><h2>Glass, steel &amp; light.</h2><p className="studio-note">27.20 × 11.25 m main rectangle, three curved bays. Eave 3.5 m and ridge 7.5 m are interpreted heights, not a survey.</p><label>Roof<select value={options.roof} onChange={e=>setOptions(o=>({...o,roof:e.target.value as ViewOptions["roof"]}))}><option value="cut">Cut away</option><option value="frame">Steel frame</option><option value="full">Glass + frame</option></select></label><label>Walls<select value={options.walls} onChange={e=>setOptions(o=>({...o,walls:e.target.value as ViewOptions["walls"]}))}><option value="low">Low cutaway</option><option value="full">Full height</option></select></label>{boolOptions.map(([key,label])=><label className="studio-check" key={key}>{label}<input type="checkbox" checked={options[key]} onChange={e=>{const checked=e.target.checked;setOptions(o=>({...o,[key]:checked}));}}/></label>)}<p className="studio-note">Inside view uses the complete envelope. In dense 3D views, names that cannot fit without overlap are counted; zoom or use a table seat map to see every guest.</p><p className="studio-note">The v5 JSON seat numbering is preserved. Labels and physical chair spacing do not certify accessibility, capacity or safe egress.</p></section>:<section><p className="studio-eyebrow">YOUR CELEBRATION, IN SPACE</p><h2>A room for everyone.</h2><div className="studio-stats"><div><strong>{layout.items.filter(t=>t.kind==="table").length}</strong><small>tables</small></div><div><strong>{layout.items.filter(t=>t.kind==="table").reduce((n,t)=>n+t.seats,0)}</strong><small>seats</small></div><div><strong>{layout.guestList.filter(g=>g.tableId).length}</strong><small>assigned</small></div></div>
      <p className="studio-note">Import your saved layout to continue the private draft. Guest names are not bundled with this public app.</p><h3>Add to the room</h3><div className="studio-palette">{kinds.map(kind=><button key={kind} onClick={()=>{const item=newItem(kind,layout.items);commit("Object added",s=>({...s,items:[...s.items,item]}));setSelected(item.id);setTab("selected");}}>+ {kind}</button>)}</div>
      <h3>Tables</h3><div className="studio-table-grid">{layout.items.filter(t=>t.kind==="table").map(t=><button key={t.id} className={selected===t.id?"active":""} onClick={()=>{setSelected(t.id);setTab("selected");}}>{t.label}<small>{tableGuests(layout,t.id).length}/{t.seats}</small></button>)}</div><h3>Event zones</h3>{layout.items.filter(t=>t.kind!=="table").map(t=><button className="studio-zone-row" key={t.id} onClick={()=>{setSelected(t.id);setTab("selected");}}>{t.label}{t.locked?" · locked":""}</button>)}
      <details><summary>{warnings.length} spatial checks</summary><p className="studio-note">Estimated footprint overlaps only. Confirm circulation with the venue.</p>{warnings.map((message,i)=><p className="studio-warning" key={i}>{message}</p>)}</details><button onClick={()=>{if(confirm("Restore the twenty-table geometry? Guest records and source references are kept; current placements are cleared. Undo is available."))commit("Reference layout restored; guests retained",s=>({...defaultLayout(),guestList:s.guestList.map(g=>({...g,tableId:"",seatNumber:null})),guestSource:s.guestSource}));}}>Restore reference layout</button><p className="studio-note">{view==="plan"?"Drag furniture in the plan or edit numeric dimensions.":"Select objects in 3D; use the floor plan for furniture dragging."}</p>
    </section>}</div>
  </aside></>;
}
