// @vitest-environment node
import { describe,it,expect } from "vitest";
import { defaultLayout } from "@/client/studio/model/defaults";
import { normalizeLayout,clone } from "@/client/studio/model/schema";
import { moveGuests } from "@/client/studio/model/commands";
import { applyMutation,mutationBetween,inverseMutation,mutationHash,mutationSchema } from "./studio-mutations";
const fixture=()=>normalizeLayout({...defaultLayout(),guestList:[{id:"test-a",name:"Synthetic A",tableId:"table-1",seatNumber:1},{id:"test-b",name:"Synthetic B",tableId:"table-1",seatNumber:2},{id:"test-c",name:"Synthetic C"}]});
describe("guarded studio mutations",()=>{
 it("swaps two seats in one operation without mutating inputs",()=>{const s=fixture(),before=clone(s),n=moveGuests(s,["test-a"],{tableId:"table-1",seatNumber:2}),op=mutationBetween(s,n);expect(op.changes).toHaveLength(2);expect(applyMutation(s,op)).toEqual(n);expect(s).toEqual(before);});
 it("merges unrelated field and guest edits",()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5})),live=clone(s);live.guestList[0].notes="Other editor note";live.guestList[2].name="Other editor name";const n=applyMutation(live,op);expect(n.guestList[0].notes).toBe("Other editor note");expect(n.guestList[2].name).toBe("Other editor name");expect(n.guestList[0].seatNumber).toBe(5);});
 it("rejects stale guest movement rather than applying the old swap",()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-a"],{tableId:"table-1",seatNumber:2})),live=moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5});expect(()=>applyMutation(live,op)).toThrow(/changed/);});
 it("rejects a destination taken by a different guest",()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5})),live=moveGuests(s,["test-c"],{tableId:"table-2",seatNumber:5});expect(()=>applyMutation(live,op)).toThrow(/target seat/);});
 it("guarded undo preserves unrelated remote notes",()=>{const s=fixture(),n=moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5}),op=mutationBetween(s,n);n.guestList[0].notes="New remote note";const undone=applyMutation(n,inverseMutation(op));expect(undone.guestList[0].seatNumber).toBe(1);expect(undone.guestList[0].notes).toBe("New remote note");});
 it("does not delete an entity changed elsewhere",()=>{const s=fixture(),n=clone(s);n.guestList=n.guestList.filter(g=>g.id!=="test-c");const op=mutationBetween(s,n),live=clone(s);live.guestList[2].notes="changed";expect(()=>applyMutation(live,op)).toThrow(/not deleted/);});
 it("keeps original references and ignores derived name caches",()=>{const s=fixture();s.guestList[0].sourceTableId="VIP2";const n=moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5}),op=mutationBetween(s,n);expect(op.changes.every(c=>c.entity==="guest")).toBe(true);expect(applyMutation(s,op).guestList[0].sourceTableId).toBe("VIP2");});
 it("can deliberately activate a reserve guest and assign them",()=>{const s=fixture();s.guestList[2].reserve=true;const n=clone(s);n.guestList[2].reserve=false;n.guestList[2].tableId="table-2";n.guestList[2].seatNumber=1;expect(applyMutation(s,mutationBetween(s,n)).guestList[2].tableId).toBe("table-2");});
 it("rejects newly changed eligibility and capacity",()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-c"],{tableId:"table-2",seatNumber:7})),live=clone(s);live.guestList[2].reserve=true;expect(()=>applyMutation(live,op)).toThrow();live.guestList[2].reserve=false;live.items[1].seats=3;expect(()=>applyMutation(live,op)).toThrow();});
 it("hashes identical payloads consistently",async()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5}));expect(await mutationHash(op)).toBe(await mutationHash(clone(op)));expect(await mutationHash({...op,id:crypto.randomUUID()})).not.toBe(await mutationHash(op));});
 it("rejects malformed and duplicate changes",()=>{const s=fixture(),op=mutationBetween(s,moveGuests(s,["test-a"],{tableId:"table-2",seatNumber:5}));expect(()=>mutationSchema.parse({...op,changes:[...op.changes,...op.changes]})).toThrow();expect(()=>mutationSchema.parse({...op,secret:"unsupported"})).toThrow();});
});
