// Static UI only. Never put guest records or invitation tokens in this module.
const button = (id: string, text: string, attrs = "") => `<button type="button" id="${id}" ${attrs}>${text}</button>`;
const field = (id: string, label: string, attrs = "", value = "") => `<label class="field">${label}<input id="${id}" ${attrs} value="${value}"></label>`;
const select = (id: string, label: string, choices: string, attrs = "") => `<label class="field">${label}<select id="${id}" ${attrs}>${choices}</select></label>`;
const opt = (value: string, text: string) => `<option value="${value}">${text}</option>`;
const switchRow = (id: string, label: string, checked = false) => `<label class="switch-row">${label}<input id="${id}" type="checkbox" ${checked ? "checked" : ""}></label>`;
const head = (id: string, title: string, close: string) => `<div class="dialog-head"><h2 id="${id}">${title}</h2>${button(close, "×", 'class="square" aria-label="Close dialog"')}</div>`;
const action = (id: string, title: string, note: string) => button(id, `<b>${title}</b><small>${note}</small>`, 'class="file-action"');

export const studioShell = `
<header class="header">
 <div class="brand"><div class="brand-name">The Glass House</div><div class="eyebrow">TONG &amp; TER · LOCAL PLANNING STUDIO</div></div>
 <nav class="view-nav" aria-label="View"><button data-view="model">◈ 3D model</button><button data-view="plan" aria-pressed="true">▦ Floor plan</button><button data-view="inside">⌂ Walk inside</button></nav>
 <div class="header-actions">${button('open-guests','♧ Guests <b id="guest-header-count">0</b>')}${button('reference','▧ Reference')}${button('save-menu','↗ Save / export','class="primary"')}</div>
</header>
<main class="workspace">
 <aside id="drawer" class="drawer">
  ${button('drawer-toggle','<span class="handle"></span><span>Wedding layout <b id="mobile-seats">200 seats</b></span><span id="drawer-chevron">⌃</span>','class="drawer-toggle" aria-expanded="false"')}
  <div class="drawer-intro"><div class="eyebrow">YOUR SPACE, REIMAGINED</div><h1>Wedding layout</h1><p id="layout-origin">Twenty-table planning draft.</p><div class="stats"><div><strong id="stat-tables">20</strong><span>TABLES</span></div><div><strong id="stat-seats">200</strong><span>SEATS</span></div><div><strong>336</strong><span>m² REFERENCE</span></div></div></div>
  <nav class="panel-tabs" aria-label="Planner panels"><button data-panel="layout" class="active">Layout</button><button data-panel="edit">Selected</button><button data-panel="guests">Guests</button><button data-panel="layers">Layers</button><button data-panel="files">Files</button></nav>
  <div class="panel-scroll">
   <section id="panel-layout" class="panel-section"><h2>Guest tables</h2><div id="table-list" class="table-list"></div><p class="hint">Click a numbered chair to assign it. Drag an occupied chair or name to move a guest; drop onto another occupant to swap.</p><h2>Event spaces</h2><div id="zone-list" class="zone-list"></div><div class="add-box"><label for="add-kind">Add to the plan</label><div class="add-row"><select id="add-kind">${opt('table','Oval table · 10 seats')}${opt('round','Round table')}${opt('stage','Stage')}${opt('runner','Straight aisle')}${opt('aisle','L-shaped aisle')}${opt('band','Band')}${opt('bar','Bar')}${opt('buffet','Buffet')}${opt('dance','Dance floor')}</select>${button('add-item','+','aria-label="Add selected object"')}</div></div>${button('checks-button','<span id="check-count">Checking layout…</span> ↗','class="check-summary"')}<p class="fine">Footprint checks are advisory, not venue capacity or safety approval.</p></section>
   <section id="panel-edit" class="panel-section" hidden><div id="edit-empty" class="empty"><h2>Select a table or space</h2><p>Use the floor plan or Layout list.</p></div><div id="edit-form" hidden><div class="selected-title"><div><div id="edit-kind" class="eyebrow"></div><h2 id="selected-name">Selected object</h2></div>${button('lock-toggle','▢','class="square"')}</div>
    ${field('edit-label','Label','data-field="label" maxlength="80"')}
    <div class="field-grid">${field('edit-x','X position (m)','data-field="x" type="number" step="0.1"')}${field('edit-z','Z position (m)','data-field="z" type="number" step="0.1"')}${field('edit-w','Width (m)','data-field="w" type="number" min="0.3" max="20" step="0.1"')}${field('edit-d','Depth (m)','data-field="d" type="number" min="0.3" max="20" step="0.1"')}${field('edit-rotation','Rotation (°)','data-field="rotation" type="number" min="-360" max="360" step="1"')}${field('edit-h','Height (m)','data-field="h" type="number" min="0.001" max="5" step="0.01"')}</div>
    <div id="table-fields" class="field-grid">${field('edit-seats','Seats','data-field="seats" type="number" min="1" max="16" step="1"')}${select('edit-shape','Shape',opt('oval','Oval')+opt('round','Round')+opt('rect','Rectangle'),'data-field="shape"')}</div>
    <label id="aisle-field" class="field" hidden>Aisle width (m)<input id="edit-aisleWidth" data-field="aisleWidth" type="number" step="0.05" min="0.4"></label>
    <div class="edit-actions">${button('rotate-item','↻ Rotate 15°')}${button('duplicate-item','⧉ Duplicate')}${button('delete-item','Remove','class="danger"')}</div>
    <details id="guests-details" open><summary>Guests <span id="guest-count"></span></summary><p id="table-guest-overview" class="fine"></p><div class="table-guest-controls">${button('table-guest-assign','Assign seat by seat')}${button('table-guest-manage','View seat map')}</div><div id="selected-guest-seats"></div></details><p id="object-warning" class="warning-text"></p><p id="lock-hint" class="fine"></p></div></section>
   <section id="panel-guests" class="panel-section" hidden><div class="section-heading"><h2>Seat your guests</h2>${button('guest-panel-open','Guestbook ↗')}</div><div class="guest-panel-stats"><div><strong id="guest-panel-total">0</strong><span>Total</span></div><div><strong id="guest-panel-assigned">0</strong><span>Seated</span></div><div><strong id="guest-panel-needs">0</strong><span>Need seats</span></div><div><strong id="guest-panel-reserve">0</strong><span>Reserve</span></div></div>
    <input id="guest-dock-search" type="search" placeholder="Search guests" aria-label="Search guests to seat"><div class="field-grid"><select id="guest-dock-filter" aria-label="Filter guests">${opt('needs','Need seats')}</select><select id="guest-dock-source" aria-label="Original group">${opt('','All original groups')}</select></div>
    <div id="guest-dock-unassigned" class="dock-unassign" data-guest-drop-table="">Drop here to unassign <strong id="guest-dock-unassigned-count">0</strong></div>
    <div class="dock-selection"><label><input id="guest-dock-select-all" type="checkbox"> Select shown</label><span id="guest-dock-count"></span></div><div class="edit-actions">${button('guest-dock-undo','↶','aria-label="Undo"')}${button('guest-dock-redo','↷','aria-label="Redo"')}${button('guest-dock-clear','Clear')}</div><div id="guest-dock-list"></div>${button('guest-dock-next','Split selected across tables','class="wide"')}<p id="guest-panel-summary" class="fine"></p>${action('guest-panel-import','↑ Import guest-table file','CSV or JSON · preview first')}${action('guest-panel-export','↓ Export & print guests','CSV, JSON and seating lists')}</section>
   <section id="panel-layers" class="panel-section" hidden><h2>Building layers</h2>${select('roof-mode','Roof',opt('none','Open · cutaway')+opt('frame','Steel structure only')+opt('glass','Complete glass roof'))}${select('wall-mode','Walls',opt('cut','Low walls · cutaway')+opt('glass','Full-height glass')+opt('frame','Frames only')+opt('none','Hidden'))}<div class="two-buttons">${button('exterior-preset','Exterior view')}${button('cutaway-preset','Cutaway view')}</div>
    ${switchRow('show-tables','Tables',true)}${switchRow('show-chairs','Numbered chairs',true)}${switchRow('show-guestNames','Guest names at seats',true)}${switchRow('show-zones','Stage, aisle & event spaces',true)}${switchRow('show-labels','Object labels',true)}${switchRow('show-decor','Hanging greenery & lanterns')}${switchRow('show-garden','Garden context',true)}<h2 class="spaced">Planning tools</h2>${switchRow('show-dimensions','Dimensions',true)}${switchRow('show-grid','1 m grid')}${switchRow('show-collisions','Footprint conflict highlights')}${switchRow('snap','Snap movement to 0.1 m',true)}${select('light-mode','Lighting',opt('day','Soft daylight')+opt('evening','Evening ambience'))}<div id="check-list" class="check-list"></div><p class="fine">Checks use approximate chair envelopes and object footprints. They do not assess accessibility, fire exits or required aisle widths.</p></section>
   <section id="panel-files" class="panel-section" hidden><h2>Keep your plans</h2><p class="hint">Import your previous standalone Layout JSON to continue. Changes are local drafts and do not change the live Google Sheet.</p>${action('export-json','Export layout','Geometry + complete guest records')}${action('import-json','Import layout','Studio v2/v3 JSON · geometry and guests')}${action('export-svg','Export floor plan','Scalable SVG · dimensions & labels')}${action('export-png','Save image','Current 3D view or high-resolution plan')}${button('export-html','<b>Save portable HTML</b><small id="portable-hint">Includes your current layout and reference</small>','class="file-action"')}${button('reset-layout','↺ Restore reference layout','class="wide"')}${button('about','Model notes & controls','class="wide"')}<p id="save-status" class="save-status">Default layout · not yet edited</p><p class="fine">2D works offline. Three.js r161 downloads on first 3D use; Save portable HTML embeds the engine after loading. Exported copies contain private guest data.</p></section>
  </div><div class="drawer-foot"><span id="engine-status">2D ready</span></div>
 </aside>
 <section id="viewport" class="viewport" aria-label="Interactive venue viewer"><div id="threeStage" class="three-stage" hidden></div><div id="planStage" class="plan-stage"></div><div class="view-caption"><span id="view-eyebrow" class="eyebrow">LAYOUT STUDY</span><h2 id="view-title">A place for everyone.</h2><p id="view-subtitle">Twenty-table planning draft.</p></div>
  <div id="engine-notice" class="engine-notice" hidden><span id="engine-notice-text"></span>${button('retry-3d','Retry 3D')}</div><div class="view-tools">${button('zoom-in','+','class="square" aria-label="Zoom in"')}${button('zoom-out','−','class="square" aria-label="Zoom out"')}${button('fit-view','⛶','class="square" aria-label="Reset view"')}${button('guest-names-toggle','Aa','class="square active" aria-label="Toggle guest names" aria-pressed="true"')}</div>
  <div id="walk-tools" class="walk-tools" hidden><div class="walk-help">Hold to walk · drag to look</div><div class="walk-pad"><button data-walk="forward" aria-label="Walk forward">↑</button><div><button data-walk="left" aria-label="Walk left">←</button><button data-walk="back" aria-label="Walk backward">↓</button><button data-walk="right" aria-label="Walk right">→</button></div></div><div class="walk-settings"><select id="walk-speed" aria-label="Walking pace">${opt('0.8','Slow stroll')}<option value="1.6" selected>Normal pace</option>${opt('2.6','Brisk walk')}</select></div>${button('walk-mouse','Mouse look')}${button('walk-home','Reset view')}</div>
  <div class="floating-toolbar">${button('seat-guests-tool','⠿ Seat guests','class="tool"')}${button('move-mode','<span>↔</span><span id="move-mode-text">Move furniture</span>','class="tool active"')}${button('roof-cycle','<span>⌂</span><span id="roof-label">Roof off</span>','class="tool"')}${button('undo','↶','class="tool icon-only" aria-label="Undo"')}${button('redo','↷','class="tool icon-only" aria-label="Redo"')}</div><div class="view-footer"><span id="gesture-hint">Click a chair to assign it.</span><span class="model-note">METRES · SCHEMATIC ONLY</span></div>
 </section>
</main>
<div id="guest-drag-status" class="sr-only" role="status" aria-live="polite"></div><div id="toast" role="status" aria-live="polite"></div><input id="import-file" type="file" accept="application/json,.json" hidden>
<dialog id="reference-dialog">${head('reference-title','Venue reference','close-reference')}<div class="reference-tabs"><button data-ref="layout">Repository seating reference</button></div><div class="reference-image-wrap"><img id="reference-image" alt="Repository venue reference"></div><p class="fine">Existing repository reference. The studio starts with the separate v5 twenty-table draft; it does not alter the guest-facing venue geometry.</p></dialog>
<dialog id="about-dialog">${head('about-title','About this planning studio','close-about')}<div class="about-body"><h3>Local drafts, separate from live seating</h3><p>Import a saved Studio layout or preview guests from the site using the toolbar above. No guest records are bundled in the public source. Changes, additions, and deletions stay in this browser until exported. They do not write to Google Sheets or change RSVP/seat-reveal pages.</p><h3>Geometry and labels</h3><p>The v5 draft uses a 27.20 m main width, 11.25 m depth, three curved bays, and 20 tables. Furniture sizes and roof details are approximations. Seat 1 begins at the unrotated right end and numbering proceeds clockwise with the table. Labels use deterministic collision avoidance; crowded plans may require zooming or a table close-up.</p><h3>Controls</h3><p>Drag furniture on the floor plan, or switch to Navigate only. Drag occupied chairs or guest labels to move guests; an occupied destination swaps seats. Escape cancels, and Undo/Redo restores assignments. Walk inside: hold WASD, arrow keys or the touch pad, drag to look, Shift for faster movement.</p><h3>Private exports</h3><p>CSV, JSON, printable lists and portable HTML include guest names and other imported guest data. Share only with intended recipients. A shared browser also retains local drafts.</p></div></dialog>
<dialog id="guest-dialog" class="guest-dialog"><div class="guest-top"><div><div class="eyebrow">GUESTBOOK</div><h2 id="guest-title">A seat for every story.</h2><p>Import, assign and keep your seating plan together.</p></div>${button('close-guests','×','class="square" aria-label="Close guestbook"')}</div><div class="guest-metrics"><div><strong id="guest-stat-total">0</strong><span>GUESTS</span></div><div><strong id="guest-stat-assigned">0</strong><span>ASSIGNED</span></div><div><strong id="guest-stat-needs">0</strong><span>NEED SEATS</span></div><div><strong id="guest-stat-reserve">0</strong><span>RESERVE</span></div><p id="guest-capacity-note"></p></div>
 <div class="guest-actionbar"><div class="guest-view-tabs">${button('guest-directory-tab','Guest list','class="active"')}${button('guest-seating-tab','By table')}${button('guest-seat-plan','Seat on plan ↗')}</div><div class="guest-top-actions">${button('guest-undo','↶','aria-label="Undo"')}${button('guest-redo','↷','aria-label="Redo"')}${button('guest-import','↑ Import')}${button('guest-export','↓ Export')}${button('guest-add','+ Add guest','class="primary"')}</div></div>
 <div id="guest-notice" class="guest-notice"></div><div id="guest-directory"><div class="guest-filters"><label class="guest-search-label"><span>Search</span><input id="guest-search" type="search" placeholder="Name, group or notes"></label><label><span>Host</span><select id="guest-host-filter">${opt('','All hosts')}</select></label><label><span>Seating</span><select id="guest-seating-filter">${opt('all','All guests')}${opt('needs','Need seats')}${opt('assigned','Assigned')}${opt('reserve','Reserve')}${opt('declined','Declined')}</select></label><label><span>Group</span><select id="guest-group-filter">${opt('','All groups')}</select></label><label><span>Original table</span><select id="guest-source-filter">${opt('','All original tables')}</select></label>${button('guest-clear-filters','Clear','class="plain"')}</div>
 <div class="guest-bulkbar"><label class="select-matched"><input id="guest-select-visible" type="checkbox"><span id="guest-matched-count">0 shown</span></label><span id="guest-selection-count">0 selected</span><div class="guest-bulk-actions" hidden><select id="guest-bulk-table" aria-label="Bulk destination">${opt('','Choose a table')}</select>${button('guest-assign-selected','Assign')}${button('guest-distribute','Split across tables')}${button('guest-unassign','Unassign')}${button('guest-remove-selected','Remove','class="danger"')}${button('guest-clear-selected','Clear selection')}</div></div>
 <div id="guest-action-error" class="guest-error" hidden role="alert"></div><div id="guest-drag-targets"></div><div class="guest-table-wrap"><table class="guest-records"><thead><tr><th>Select</th><th>Guest</th><th>RSVP</th><th>Original table</th><th>Seat</th><th>Edit</th></tr></thead><tbody id="guest-rows"></tbody></table><div id="guest-empty" class="guest-empty">No guests match. Add a guest or import your saved roster.</div></div></div>
 <div id="guest-by-table" hidden><p class="guest-board-intro">Drag a guest onto an empty seat to assign. Move a seated guest onto an occupied seat to swap.</p><aside class="guest-board-pool"><h3>Unassigned <strong id="board-unassigned-count">0</strong></h3><input id="guest-board-search" type="search" placeholder="Search unassigned" aria-label="Search unassigned guests"><div class="dock-unassign" data-guest-drop-table="">Drop to unassign</div><div id="guest-board-pool-list"></div></aside><div id="guest-table-board"></div></div><div class="guest-bottom"><span id="guest-bottom-summary"></span><span>Local draft · no live Sheet writes</span></div>
</dialog>
<dialog id="guest-form-dialog" class="guest-small-dialog">${head('guest-form-title','Add guest','guest-form-close')}<form id="guest-form-form"><div id="guest-form-error" class="guest-error" hidden role="alert"></div>${field('gf-name','Name','required maxlength="100" autocomplete="off"')}<div class="field-grid">${field('gf-host','Host','list="guest-hosts" maxlength="40"')}${field('gf-group','Group','list="guest-groups" maxlength="120"')}${field('gf-status','Invitation status','list="guest-statuses" maxlength="80"')}${select('gf-rsvp','RSVP',['Pending','Confirmed','Maybe','Declined'].map(v=>opt(v,v)).join(''))}</div><div class="guest-flags"><label><input id="gf-important" type="checkbox"> ♥ Important</label><label><input id="gf-vip" type="checkbox"> ★ VIP</label><label><input id="gf-reserve" type="checkbox"> Reserve</label></div><div class="field-grid">${select('gf-table','Table',opt('','Unassigned'))}${select('gf-seat','Seat',opt('','Next free seat'))}</div>${field('gf-dietary','Dietary notes','maxlength="300"')}<label class="field">Notes<textarea id="gf-notes" rows="3" maxlength="2000"></textarea></label><div id="guest-form-source" class="guest-source-note"></div><div id="guest-name-warning" class="guest-source-note" hidden></div><div class="guest-form-actions">${button('guest-delete-one','Remove guest','class="danger"')}<div>${button('guest-form-cancel','Cancel')}<button id="guest-form-save" class="primary" type="submit">Save guest</button></div></div></form></dialog>
<dialog id="guest-distribute-dialog" class="guest-small-dialog guest-medium-dialog">${head('distribution-title','Split across tables','distribution-close')}<p id="distribution-description" class="hint"></p><div id="distribution-table-grid"></div><div id="distribution-error" class="guest-error" hidden role="alert"></div><div id="distribution-preview"></div><div class="guest-form-actions"><span id="distribution-free"></span>${button('distribution-apply','Apply seating','class="primary" disabled')}</div></dialog>
<dialog id="guest-import-dialog" class="guest-small-dialog guest-medium-dialog">${head('guest-import-title','Import guest tables','guest-import-close')}<p id="guest-import-filename"></p>${select('guest-import-mode','Import mode',opt('merge','Merge · update matching IDs, add new IDs')+opt('replace','Replace the entire guest list'))}<div id="guest-import-warnings"></div><div id="guest-import-error" class="guest-error" hidden role="alert"></div><div id="guest-import-summary"></div><label id="guest-import-replace-label" class="guest-confirm-check" hidden><input id="guest-import-replace-confirm" type="checkbox"> I understand this replaces the current guest list.</label><div class="guest-form-actions">${button('guest-import-cancel','Cancel')}${button('guest-import-apply','Apply import','class="primary" disabled')}</div></dialog>
<dialog id="guest-export-dialog" class="guest-small-dialog">${head('guest-export-title','Keep a copy.','guest-export-close')}${action('guest-export-csv','Guest-table CSV','Spreadsheet editing · UTF-8 names')}${action('guest-export-json','Guest-table JSON','Complete guest records · lossless')}${action('guest-export-html','Save complete standalone app','Current venue layout, guests and assignments')}${action('guest-print','Printable seating lists','Per-table lists plus unassigned pool')}<p class="fine">Exports contain private guest information.</p></dialog>
<dialog id="guest-confirm-dialog" class="guest-small-dialog"><h2 id="guest-confirm-title">Confirm change</h2><p id="guest-confirm-text" class="hint"></p><div class="guest-form-actions">${button('guest-confirm-cancel','Cancel')}${button('guest-confirm-apply','Confirm','class="primary"')}</div></dialog>
<input id="guest-import-file" type="file" accept=".csv,.json,text/csv,application/json" hidden><datalist id="guest-hosts"><option value="Tong"><option value="Ter"></datalist><datalist id="guest-groups"></datalist><datalist id="guest-statuses"><option value="Not invited"><option value="Invited"></datalist>
<div id="seat-tooltip" role="tooltip" hidden></div>
<dialog id="seat-map-dialog" class="seat-map-dialog"><header class="seat-map-header"><div><div class="eyebrow">SEAT BY SEAT</div><h2 id="seat-map-title">Table seats</h2></div><div class="seat-map-header-actions"><select id="seat-map-table" aria-label="Choose table"></select>${button('seat-map-close','×','class="square" aria-label="Close seat map"')}</div></header><div class="seat-map-body"><section class="seat-map-visual"><div class="seat-map-summary"><span id="seat-map-occupancy"></span><div class="seat-legend"><span>● Assigned</span><span>○ Empty</span></div></div><div class="seat-name-controls"><span>Drag chairs or names to move guests.</span>${button('seat-names-toggle','Names','class="active" aria-pressed="true"')}</div><div id="seat-map-diagram" class="seat-map-diagram"></div><p class="seat-orientation">Names follow their exact numbered chairs. Top matches the floor plan.</p><div class="seat-roster-heading"><h3>Who sits where</h3><span>Click to select · drag to move</span></div><div id="seat-map-roster" class="seat-map-roster"></div></section>
 <section class="seat-map-editor"><div class="seat-map-current-head"><div><div id="seat-current-table" class="eyebrow"></div><h3 id="seat-current-title">Seat 1</h3></div><div class="seat-stepper">${button('seat-previous','←','aria-label="Previous seat"')}${button('seat-next','→','aria-label="Next seat"')}</div></div><div id="seat-current-guest" class="seat-current-guest empty"></div><div class="seat-current-actions">${button('seat-edit-guest','Edit guest')}${button('seat-clear','Clear seat')}${button('seat-add-new','+ New guest here')}</div><div class="seat-picker-heading"><h3>Assign a guest</h3><span id="seat-candidate-count"></span></div><div class="seat-picker-filters"><input id="seat-guest-search" type="search" placeholder="Search name, host or group" aria-label="Search guest for seat"><select id="seat-guest-filter" aria-label="Filter candidates">${opt('unassigned','Unassigned guests')}${opt('all','All active guests')}${opt('seated','Seated guests')}</select></div><div id="seat-candidates" class="seat-candidates"></div><div id="seat-map-error" class="guest-error" hidden role="alert"></div><div class="seat-assignment"><p id="seat-assignment-preview">Choose a guest above.</p><label><input id="seat-auto-next" type="checkbox" checked> Go to the next empty seat</label>${button('seat-apply','Assign to seat','class="primary wide" disabled')}</div></section></div><footer class="seat-map-footer"><span id="seat-map-status" role="status"></span><div>${button('seat-map-undo','↶ Undo')}${button('seat-map-redo','↷ Redo')}${button('seat-map-export','Export this table')}</div></footer></dialog>
`;
